version: "3.7"

services:
  db:
    container_name: mongo-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=auth
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - mongo_data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - db
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8082:8081'

networks:
  mongo-compose-network:

volumes:
  mongo_data:
