version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  python-app:
    build:
      context: .
    container_name: python-app
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    command: ["mongodb:27017", "--", "python", "/app/feed_to_mondodb.py"]

volumes:
  mongodb_data:
