channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=23.3.2
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - psutil==5.9.7
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
