global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "airline-project"

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'docker_engine'
    static_configs:
      - targets: ['192.168.10.49:9323']
  
  - job_name: 'airflow_statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.10.49:8002']
